### ISSUE TITLE
设置 Key 的时候多加了 "Bearer "

### ISSUE THREAD

**Issue by JiyeHoo** [mingzhennanqu/ChatGptDemo#1]
SetDialogKey 里面保存到 SharedPreferences 的时候多加了 "Bearer "，
在 chatCreate 方法 Api 请求的时候在 Authorization 中又重复加了前缀 "Bearer "。
应该将 SetDialogKey 保存时候去掉 "Bearer "，否则 chatCreate 请求会一直报错的。

另外，建议将代码整理一下～
"微信防撤回"之类的字段和多余的 PNG 删了吧（CV起来不方便呀）～

**Comment by mingzhennanqu** [comment]
好的，感谢指出

**Comment by mingzhennanqu** [comment]
我修改了请求头，在请求头加上了Bearer字段，后续忘记修改SharedPreferences 了，不好意思，已修改
